package gui;

import javax.swing.*;

public class login {
    private JPanel panel1;
    private JTextField textField1;
    private JPasswordField passwordField1;
    private JButton loginButton;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.jgoodies.forms.layout.FormLayout("fill:d:grow,left:0dlu:grow(0.5),fill:d:grow,fill:d:grow(0.1)", "center:142px:grow,center:194px:grow,center:max(d;4px):noGrow,center:d:grow(0.19999999999999998)"));
        panel1.setEnabled(true);
        final JLabel label1 = new JLabel();
        label1.setText("Username:");
        com.jgoodies.forms.layout.CellConstraints cc = new com.jgoodies.forms.layout.CellConstraints();
        panel1.add(label1, cc.xy(1, 1, com.jgoodies.forms.layout.CellConstraints.CENTER, com.jgoodies.forms.layout.CellConstraints.DEFAULT));
        passwordField1 = new JPasswordField();
        panel1.add(passwordField1, cc.xy(3, 2, com.jgoodies.forms.layout.CellConstraints.FILL, com.jgoodies.forms.layout.CellConstraints.DEFAULT));
        textField1 = new JTextField();
        textField1.setText("");
        panel1.add(textField1, cc.xy(3, 1, com.jgoodies.forms.layout.CellConstraints.FILL, com.jgoodies.forms.layout.CellConstraints.DEFAULT));
        final JLabel label2 = new JLabel();
        label2.setText("Password:");
        panel1.add(label2, cc.xy(1, 2, com.jgoodies.forms.layout.CellConstraints.CENTER, com.jgoodies.forms.layout.CellConstraints.DEFAULT));
        loginButton = new JButton();
        loginButton.setText("Login");
        panel1.add(loginButton, cc.xy(2, 3, com.jgoodies.forms.layout.CellConstraints.CENTER, com.jgoodies.forms.layout.CellConstraints.DEFAULT));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer1, cc.xy(2, 4, com.jgoodies.forms.layout.CellConstraints.DEFAULT, com.jgoodies.forms.layout.CellConstraints.FILL));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer2, cc.xy(4, 1, com.jgoodies.forms.layout.CellConstraints.FILL, com.jgoodies.forms.layout.CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
