package src.view;

import src.controller.Controller;
import src.objects.Department;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ManageDepartments extends Form {
    private JPanel panel1;
    private JButton createDepartmentButton;
    private JList list1;
    private JButton deleteDepartmentButton;
    private DefaultListModel<String> departmentsModel;

    public ManageDepartments(GUIFrame frame) {
        super(frame);
        setJPanel(panel1);
        departmentsModel = new DefaultListModel<>();
        frame.setTitle("Manage Departments");

        for (Department department : Controller.getDepartments()) {
            departmentsModel.addElement(department.getCode());
        }

        list1.setModel(departmentsModel);
        list1.setVisibleRowCount(10);
        createDepartmentButton.addActionListener(new DepartmentHandler());
        deleteDepartmentButton.addActionListener(new RemoveDepartmentHandler());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        final JScrollPane scrollPane1 = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(scrollPane1, gbc);
        list1 = new JList();
        scrollPane1.setViewportView(list1);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer2, gbc);
        deleteDepartmentButton = new JButton();
        deleteDepartmentButton.setText("Delete Selected Departments");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(deleteDepartmentButton, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer3, gbc);
        createDepartmentButton = new JButton();
        createDepartmentButton.setText("Create Department");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(createDepartmentButton, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("List of Departments");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        panel1.add(label1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    public class DepartmentHandler implements ActionListener {
        public void actionPerformed(ActionEvent actionEvent) {
            changeJPanel(new CreateDepartment(getFrame()).getJPanel());
        }
    }

    private class RemoveDepartmentHandler implements ActionListener {
        public void actionPerformed(ActionEvent actionEvent) {
            for (Object code : list1.getSelectedValuesList()) {
                Controller.removeDepartment((String) code);
            }
            changeJPanel(new ManageDepartments(getFrame()).getJPanel());
        }
    }

}
